import type { MonthData, DashboardSettings } from './types'
import { omr, pct, fmt } from './aggregations'

export function generateWhatsAppSummary(data: MonthData, settings: DashboardSettings): string {
  const mPct = data.totRev ? data.totMarg / data.totRev * 100 : 0
  const custs = Object.values(data.custs).sort((a, b) => b.rev - a.rev)
  const top = custs[0]
  const parts = Object.values(data.parts).sort((a, b) => b.rev - a.rev)
  const topPart = parts[0]
  const conc = data.totRev && top ? top.rev / data.totRev * 100 : 0

  const alerts: string[] = []
  if (conc > settings.concentrationWarnPct) alerts.push(`High concentration: ${top?.name} = ${pct(conc)} of revenue`)
  const zeroM = Object.values(data.parts).filter(p => p.rev > 0 && p.marg / p.rev * 100 < 1)
  if (zeroM.length > 0) alerts.push(`${zeroM.length} parts at zero margin — review pricing`)
  if (mPct < settings.marginWarnPct) alerts.push(`Margin ${pct(mPct)} below target of ${settings.marginWarnPct}%`)

  return `📊 *HMI Parts — ${data.month} Report*

💰 Revenue: ${omr(data.totRev)}
📈 Gross Margin: ${pct(mPct)}
🧾 Invoices: ${fmt(data.totInv)}
👥 Customers: ${fmt(data.uCusts)}
📦 Parts: ${fmt(data.uParts)}
🏷️ VAT Collected: ${omr(data.totVAT)}

🏆 Top Customer: ${top?.name || '—'} (${omr(top?.rev || 0)})
🔩 Best Part: ${topPart?.name || '—'} (${omr(topPart?.rev || 0)})

${alerts.length ? '⚠️ *Alerts:*\n' + alerts.map(a => `• ${a}`).join('\n') : '✅ No critical alerts this month'}

_Generated by HMI Sales Intelligence_`.trim()
}

export async function exportToExcel(data: MonthData): Promise<void> {
  const XLSX = await import('xlsx')
  const wb = XLSX.utils.book_new()

  // Summary
  const sumRows = [
    ['HMI Parts Sales Report — ' + data.month], [''],
    ['Metric', 'Value'],
    ['Total Revenue', data.totRev],
    ['Total Margin', data.totMarg],
    ['Gross Margin %', data.totRev ? +(data.totMarg / data.totRev * 100).toFixed(2) : 0],
    ['Total COGS', data.totCOGS],
    ['VAT Collected', data.totVAT],
    ['Total Invoices', data.totInv],
    ['Unique Customers', data.uCusts],
    ['Unique Parts', data.uParts],
    ['Avg Order Value', data.totInv ? +(data.totRev / data.totInv).toFixed(2) : 0],
  ]
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(sumRows), 'Summary')

  // Customers
  const custRows = [
    ['Customer', 'Revenue (OMR)', 'Margin (OMR)', 'Margin %', 'Invoices', 'Avg Invoice'],
    ...Object.values(data.custs).sort((a, b) => b.rev - a.rev).map(c => {
      const mp = c.rev ? +(c.marg / c.rev * 100).toFixed(2) : 0
      const ai = c.invs.size ? +(c.rev / c.invs.size).toFixed(2) : 0
      return [c.name, +c.rev.toFixed(2), +c.marg.toFixed(2), mp, c.invs.size, ai]
    })
  ]
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(custRows), 'Customers')

  // Parts
  const partRows = [
    ['Part Name', 'Qty Sold', 'Revenue (OMR)', 'Margin (OMR)', 'Margin %'],
    ...Object.values(data.parts).sort((a, b) => b.rev - a.rev).map(p => {
      const mp = p.rev ? +(p.marg / p.rev * 100).toFixed(2) : 0
      return [p.name, p.qty, +p.rev.toFixed(2), +p.marg.toFixed(2), mp]
    })
  ]
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(partRows), 'Parts')

  // Daily
  const dailyRows = [
    ['Day', 'Revenue (OMR)', 'Margin (OMR)', 'COGS (OMR)', 'Margin %', 'Invoices'],
    ...Object.values(data.daily).sort((a, b) => a.day - b.day).map(d => {
      const mp = d.rev ? +(d.marg / d.rev * 100).toFixed(2) : 0
      return [d.day, +d.rev.toFixed(2), +d.marg.toFixed(2), +d.cogs.toFixed(2), mp, d.invs.size]
    })
  ]
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(dailyRows), 'Daily')

  XLSX.writeFile(wb, `HMI_${data.month.replace(/\s/g, '_')}_Report.xlsx`)
}
